// <auto-generated />
namespace LeagueSeason5CountersService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddCounters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCounters));
        
        string IMigrationMetadata.Id
        {
            get { return "201507270158309_AddCounters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
